#!/bin/bash
# Embed res/version.txt as a compile-time constant.
#
# The value is interpolated straight into a C++ initialiser, so anything in
# res/version.txt becomes code: "0; /* ... */" would compile. Validate that it is
# a plain unsigned integer before writing the header.
set -euo pipefail

VERSION_PATH="./res/version.txt"
OUT="src/version.hpp"

[ -f "$VERSION_PATH" ] || {
	echo "embed-version: $VERSION_PATH not found" >&2
	exit 1
}

VERSION="$(tr -d '[:space:]' < "$VERSION_PATH")"

if ! [[ "$VERSION" =~ ^[0-9]+$ ]]; then
	echo "embed-version: $VERSION_PATH must contain only digits (got '${VERSION}') -- refusing to generate $OUT" >&2
	exit 1
fi
# uint64_t range. A longer run of digits would silently overflow the constant.
if [ "${#VERSION}" -gt 20 ]; then
	echo "embed-version: $VERSION_PATH does not fit in a uint64_t -- refusing to generate $OUT" >&2
	exit 1
fi

{
	printf '// Generated by embed-version.sh from %s. Do not edit.\n' "$VERSION_PATH"
	printf '#pragma once\n'
	printf '#include <cstdint>\n'
	printf 'constexpr uint64_t VERSION = %sULL;\n' "$VERSION"
} > "$OUT"
