#!/bin/bash
# Embed res/config.yaml as a C++ raw string literal.
#
# The generated header is compiled, so the YAML's contents become code. With the
# default R"(...)" delimiter, a `)"` anywhere in res/config.yaml closes the
# literal and everything after it is compiled as C++ — a supply-chain vector that
# a review of a YAML change would not be looking for. Use an unlikely delimiter
# and REFUSE to generate anything when the input contains its terminator.
set -euo pipefail

CONFIG_PATH="./res/config.yaml"
OUT="src/config_default.hpp"
DELIM="SLSCFG"

[ -f "$CONFIG_PATH" ] || {
	echo "embed-config: $CONFIG_PATH not found" >&2
	exit 1
}

CONFIG="$(cat "$CONFIG_PATH")"

if printf '%s' "$CONFIG" | grep -qF ")$DELIM\""; then
	echo "embed-config: $CONFIG_PATH contains the raw-string terminator )$DELIM\" -- refusing to generate $OUT" >&2
	exit 1
fi
# A raw string literal cannot contain a carriage return either; a CRLF file would
# produce a header that does not compile, or worse compiles differently.
if printf '%s' "$CONFIG" | grep -q $'\r'; then
	echo "embed-config: $CONFIG_PATH contains carriage returns -- refusing to generate $OUT" >&2
	exit 1
fi

{
	printf '// Generated by embed-config.sh from %s. Do not edit.\n' "$CONFIG_PATH"
	printf '#pragma once\n'
	printf 'static const char* defaultConfig = R"%s(%s)%s";\n' \
		"$DELIM" "$CONFIG" "$DELIM"
} > "$OUT"
