// Generated by embed-config.sh from ./res/config.yaml. Do not edit.
#pragma once
static const char* defaultConfig = R"SLSCFG(#Example AppIds Config for those not familiar with YAML:
#AppIds:
#  - 440
#  - 730
#Take care of not messing up your spaces! Otherwise it won't work

#Example of DlcData:
#DlcData:
#  AppId:
#    FirstDlcAppId: "Dlc Name"
#    SecondDlcAppId: "Dlc Name"

#Example of DenuvoGames:
#DenuvoGames:
#  SteamId:
#    -  AppId1
#    -  AppId2

#Example of FakeAppIds:
#FakeAppIds:
#  AppId1: FakeAppId1
#  AppId2: FakeAppId2

#Disables Family Share license locking for self and others
DisableFamilyShareLock: yes

#Locally unlocks Steam areas restricted by parental controls. Requires restart.
DisableParentalRestrictions: no

#Switches to whitelist instead of the default blacklist
UseWhitelist: no

#Automatically filter Apps in CheckAppOwnership. Filters everything but Games and Applications. Should not affect DLC checks
#Overrides black-/whitelist. Gets overriden by AdditionalApps
AutoFilterList: yes

#List of AppIds to ex-/include
AppIds:

#Enables playing of not owned games. Respects black-/whitelist AppIds
PlayNotOwnedGames: no

#DO NOT ADD APPIDS HERE. Recent slsteam-moon versions read the game list
#directly from ~/.steam/steam/config/stplug-in. To add AppIDs manually
#(without relying on stplug-in), use ~/.config/SLSsteam/luaappids.yaml.
#This section is kept only for backward compatibility and will be removed
#in future versions.
AdditionalApps:

#Extra Data for Dlcs belonging to a specific AppId. Only needed
#when the App you're playing is hit by Steams 64 DLC limit
DlcData:

#Used to retrieve ProductInfo from Steam servers for some games
AppTokens:

#Fake Steam being offline for specified AppIds. Same format as AppIds
FakeOffline:

#Change AppIds of games to enable networking features
#Use 0 as a key to set for all unowned Apps
#Do not run multiple apps under the same AppId simultaneously! It's possible but
#will most likely cause undefined behaviour
#Requires access to /proc to read processes' real AppId from their environment (most distros allow this by default)
FakeAppIds:

#Custom ingame statuses. Set AppId to 0 to disable
IdleStatus:
  AppId: 0
  Title: ""

#Override game titles. Only works with owned appIds! For injected appIds use either UnownedStatus or combine them with FakeAppIds
GameTitles:

#Override purchase time stamps
SubscriptionTimestamps:

#Blocks games from unlocking on wrong accounts
DenuvoGames:

#Overrides your SteamId an app sees. Only needed when the automatic SteamId spoofing
#fails (some games do call GetSteamId before they request your ticket)
#Also can be used to workaround locked saves
#Either set to SteamId or to 0 to use the SteamId in the cached AppOwnershipTicket
SteamIdOverride:

#Makes steamId spoofing a lot smarter than the default by analyzing
#an executable that freshly connected to the Steamclient. This might slow down game
#startup times on slower disks (less than 10ms for SteamDRM, up to 20-2000ms for Denuvo on my SSD)
#Requires access to /proc/gamepid
#Created the same way as LogLevels
#SteamDRM = 0x1
#Denuvo = 0x2
SmartTickets: 0x1

#Automatically disable SLSsteam when steamclient.so does not match a predefined file hash that is known to work
#You should enable this if you're planing to use SLSsteam with Steam Deck's gamemode
#DEPRECATED / no-op: this option is force-disabled in code. The Steam wrapper's
#crash-loop fail-safe now covers the Game Mode boot protection this guarded, so
#an unknown client hash no longer disables SLSsteam. Setting it has no effect.
SafeMode: no

#Toggles notifications via notify-send
Notifications: yes

#Warn user via notification when steamclient.so hash differs from known safe hash
#Mostly useful for development so I don't accidentally miss an update
WarnHashMissmatch: no

#Notify when SLSsteam is done initializing
NotifyInit: yes

#Enable sending commands to SLSsteam via /tmp/SLSsteam.API
API: no

#Disable cloud saves for unlocked games. Default "no" so CloudRedirect (shipped
#with this stack) can sync saves to your own provider. Set to "yes" if you are
#NOT using CloudRedirect, to avoid a doomed cloud sync that Steam rejects.
DisableCloud: no

#Keep managed games on the latest build. Default "yes" (games auto-update).
#Set to "no" to lock every managed game to its currently installed build (like
#LuaTools' "Auto Update Apps" toggle). Builds you pin per game still apply.
AutoUpdateApps: yes

# Share short-lived manifest request codes for depots this account really owns.
# The wanted list is downloaded from the archive; only matching depots are sent.
# Set Enabled: no to disable both active requests and passive capture.
Donate:
  Enabled: yes
  Url: "https://manifest.luastools.xyz"
  IntervalSecs: 30
  WantedRefreshSecs: 300
  MaxMintsPerCycle: 25
  MinMintIntervalMs: 2000
  MaxMintsPerSession: 0 # 0 means no session cap

# Inject every storefront-advertised DLC into package 0. Keep disabled by
# default; content-backed DLC is still injected automatically.
InjectAllAdvertisedDlc: no

#Show achievements for unowned games. Steam only returns a game's achievement
#schema to an account that owns it, so the schema is sourced from an owner (see
#AchievementOwnerId). Set to "no" to disable achievement schema spoofing.
Achievements: yes

#Fallback account (SteamID64) used to read achievement schemas when a game has
#no per-game override in AchievementOwners. Only the public schema is read; the
#account is never signed in to.
AchievementOwnerId: 76561198028121353

#Per-game override of the achievement-schema source account. Same shape as
#FakeAppIds:
#AchievementOwners:
#  AppId: SteamID64
AchievementOwners:

# Local pattern cache keyed by GNU build-id, module size, and mtime. Each
# cached signature is rechecked before an address is accepted.
PatternCache: yes

# Refresh existing appinfo buffers from the PICS worker after Steam starts.
# Apps without a complete cache still use the synchronous PICS fallback.
AsyncProvision: yes

# Safety valve for accidental bulk copies into config/stplug-in, NOT a limit on
# how many games you can have. Steam's own license and appinfo reconciliation
# stalls for minutes when tens of thousands of scripts are dropped in at once,
# so only this many scripts are activated per session.
#
# The default sits far above any realistic library, and priority always goes to
# luaappids.yaml entries, games already installed on disk, and games already
# active in the session. Scripts beyond the limit are NEVER deleted: they stay
# on disk and activate as soon as the set shrinks or you raise this value.
# Set to 0 to disable the limit entirely.
MaxManagedApps: 4096

#Changes your account's E-Mail clientsided. Leave blank to disable
FakeEmail: ""

#Changes your wallet's balance clientsidedly. 0 to turn off
FakeWalletBalance: 0

#Log levels:
#Once = 0
#Debug = 1
#Info = 2
#NotifyShort = 3
#NotifyLong = 4
#Warn = 5
#None = 6
LogLevel: 2

#Logs all calls to Steamworks (this makes the logfile huge! Only useful for debugging/analyzing
ExtendedLogging: no)SLSCFG";
